set nocompatible	" be iMproved
filetype off		" required!

set t_Co=256
set rtp+=~/.vim/bundle/vundle/
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My bundles here
Bundle 'https://github.com/scrooloose/syntastic'
Bundle 'https://github.com/klen/python-mode'
Bundle 'https://github.com/ervandew/supertab'
Bundle 'https://github.com/msanders/snipmate.vim'
Bundle 'https://github.com/corntrace/bufexplorer'
Bundle 'https://github.com/Lokaltog/powerline'
Bundle 'https://github.com/airblade/vim-gitgutter'
Bundle 'https://github.com/jmcantrell/vim-virtualenv'
Bundle 'https://github.com/sjbach/lusty'
Bundle 'https://github.com/vim-scripts/Color-Sampler-Pack'

filetype plugin indent on	" required!
set cursorline
set colorcolumn=96
set hidden
set number
set nobackup
set noswapfile
set ignorecase smartcase
set expandtab
set shiftwidth=4
set tabstop=4

" Plugin configurations

" SuperTab
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" Syntastic
"let g:syntastic_python_checkers = ['pylint', 'flake8']
"let g:syntastic_python_pylint_args="--disable=W0403,W0232,E1101"
let g:syntastic_python_checkers=['flake8']

" Python Mode (https://https://github.com/klen/python-mode)
" Disable code syntax verification (Syntastic is on it)
let g:pymode_lint = 0

" Close documentation window after autocompletion
" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Powerline
" Make powerline appear on everybuffer
set laststatus=2

" Python indent/syntax/anything
source ~/.vimrc.python

" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
