set nocompatible	" be iMproved, required
filetype off		" required

" set the runtime path to include Vundle and initialize
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
set rtp+=~/Dropbox/Pessoal/dev/config_files/vim/bundle/Vundle.vim
call vundle#begin('~/Dropbox/Pessoal/dev/config_files/vim/bundle')

"set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" My bundles here
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" Bundle 'https://github.com/scrooloose/syntastic'
" Bundle 'https://github.com/klen/python-mode'
" Bundle 'https://github.com/ervandew/supertab'
" Bundle 'https://github.com/msanders/snipmate.vim'
" Bundle 'https://github.com/corntrace/bufexplorer'
" Bundle 'https://github.com/Lokaltog/powerline'
" Bundle 'https://github.com/airblade/vim-gitgutter'
" Bundle 'https://github.com/jmcantrell/vim-virtualenv'
" Bundle 'https://github.com/sjbach/lusty'
" Bundle 'https://github.com/vim-scripts/Color-Sampler-Pack'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on	" required!
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set cursorline
set colorcolumn=96
set hidden
set number
set nobackup
set noswapfile
set ignorecase smartcase
set expandtab
set shiftwidth=4
set tabstop=4

" Plugin configurations

" SuperTab
" au FileType python set omnifunc=pythoncomplete#Complete
" let g:SuperTabDefaultCompletionType = "context"
" set completeopt=menuone,longest,preview

" Syntastic
" let g:syntastic_python_checkers = ['pylint', 'flake8']
" let g:syntastic_python_pylint_args="--disable=W0403,W0232,E1101"
" let g:syntastic_python_checkers=['flake8']

" Python Mode (https://https://github.com/klen/python-mode)
" Disable code syntax verification (Syntastic is on it)
" let g:pymode_lint = 0

" Close documentation window after autocompletion
" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
" autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
" autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Powerline
" Make powerline appear on everybuffer
" set laststatus=2

" Python indent/syntax/anything
" source ~/.vimrc.python
